import { Article } from '@/types';

export const SPORTS_CONTRAST_ARTICLE: Article = {
  id: 'art-sports-001',
  title: 'Hype vs. Podium: Did the Silver Medalist Receive 4x More Brand Endorsements Than the Gold Medalist?',
  summary: 'An investigation into commercial sponsorship disparities between Olympic medalists, tracking social engagement, broadcast airtime, and verified brand disclosure filings.',
  bodyParagraphs: [
    'A viral comparison of two Olympic homecomings asks whether commercial attention followed the silver medalist more aggressively than the gold medalist.',
    'CivicLens reviewed advertising disclosures, agency announcements, broadcast monitoring logs, and the public sports-reward circular before separating documented contracts from claims that still need verification.',
    'The strongest records support a substantial difference in announced brand activity. They do not, however, establish that the government withheld the gold medalist’s reward allocation.',
  ],
  sourceName: 'CivicLens Sports Desk',
  author: 'National Sports Bureau Desk',
  publishedAt: '2026-09-25T10:30:00Z',
  category: 'Sports & Media Ethics',
  location: {
    area: 'National Sports Bureau',
    district: 'National Sports Division',
    state: 'India',
    country: 'India',
  },
  imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=1200&auto=format&fit=crop',
  imageCaption: 'Athletes competing under stadium lights during a national sporting event.',
  claimsCount: 4,
  unresolvedQuestionsCount: 2,
  citizenReportsCount: 0,
  claims: [
    {
      id: 'claim-sports-001',
      claimText: 'The silver medalist secured 14 new commercial brand contracts within 30 days of the finals, while the gold medalist signed 3.',
      speakerOrSource: 'ASCI corporate registry and agency press releases',
      status: 'Well-supported',
      statusExplanation: 'The count is supported by dated corporate disclosures and matching agency announcements reviewed by the CivicLens desk.',
      evidence: [
        {
          id: 'ev-sports-001',
          type: 'Official document',
          title: 'ASCI corporate disclosure index',
          description: 'Dated sponsorship disclosures and agency releases associated with both athletes.',
          sourceUrl: 'https://www.ascionline.in/',
          date: '2026-09-20',
          uploaderPseudonym: 'SportsDesk_Verified',
          provenanceNote: 'Cross-referenced against public corporate filings and agency release dates.',
        },
      ],
      missingInformation: [],
      generatedQuestions: ['Were all 17 agreements active contracts or did some represent campaign renewals?'],
    },
    {
      id: 'claim-sports-002',
      claimText: 'The national broadcast network allocated 78% more prime-time coverage to the silver medalist’s homecoming.',
      speakerOrSource: 'Independent broadcast media monitoring agency',
      status: 'Supported with context',
      statusExplanation: 'The monitoring log supports a higher share of measured prime-time minutes, but the sample covers one network and a defined homecoming window.',
      evidence: [
        {
          id: 'ev-sports-002',
          type: 'Dataset',
          title: 'Prime-time homecoming monitoring log',
          description: 'Time-coded broadcast minutes collected during the 48-hour comparison window.',
          sourceUrl: 'https://example.org/media-monitoring/sports-homecomings',
          date: '2026-09-19',
          uploaderPseudonym: 'MediaWatch_India',
          provenanceNote: 'Independent monitoring log; network-wide archive access is still incomplete.',
        },
      ],
      missingInformation: ['Comparable regional-language network minutes.', 'Full methodology for classifying repeat segments.'],
      generatedQuestions: ['Does the difference persist after including regional and digital broadcasts?'],
    },
    {
      id: 'claim-sports-003',
      claimText: 'The government sports development scheme withheld state prize allocation from the gold medalist.',
      speakerOrSource: 'Viral social media post',
      status: 'Contradicted by available evidence',
      statusExplanation: 'The Ministry of Sports circular records a direct bank transfer of the ₹5 Crore grant, contradicting the withholding claim.',
      evidence: [
        {
          id: 'ev-sports-003',
          type: 'Official document',
          title: 'Ministry sports reward circular',
          description: 'Public gazette circular documenting the approved reward and direct transfer record.',
          sourceUrl: 'https://sportsauthorityofindia.nic.in/',
          date: '2026-09-18',
          uploaderPseudonym: 'CivicAuditor',
          provenanceNote: 'Official ministry circular published in the public sports-reward archive.',
        },
      ],
      missingInformation: [],
      generatedQuestions: ['Was any separate state-level honorarium delayed despite the national grant?'],
    },
    {
      id: 'claim-sports-004',
      claimText: 'The silver medalist’s follower growth exceeded the gold medalist by 500% in 48 hours.',
      speakerOrSource: 'Unaudited social API scraping snapshots',
      status: 'Needs verification',
      statusExplanation: 'The screenshots show a sharp difference, but they do not provide an auditable API methodology, baseline timestamps, or bot-adjusted counts.',
      evidence: [
        {
          id: 'ev-sports-004',
          type: 'External source',
          title: 'Social growth comparison snapshots',
          description: 'Unaudited screenshots claiming a 48-hour follower-growth comparison.',
          date: '2026-09-21',
          uploaderPseudonym: 'OpenDataObserver',
          provenanceNote: 'Community-submitted snapshots; platform export and collection method not supplied.',
        },
      ],
      missingInformation: ['Platform export with timestamps.', 'Bot and duplicate-account adjustment methodology.'],
      generatedQuestions: ['What were the verified baseline counts immediately before the finals?'],
    },
  ],
};
