import { Article } from '@/types';

export const SPORTS_CONTRAST_ARTICLE: Article = {
  isDemo: true,
  id: 'art-sports-001',
  title: 'Hype vs. Podium: Did the Silver Medalist Receive 4x More Brand Endorsements Than the Gold Medalist?',
  summary: 'An investigation into commercial sponsorship disparities between Olympic medalists, tracking social engagement, broadcast airtime, and verified brand disclosure filings.',
  bodyParagraphs: [
    'A viral comparison of two Olympic homecomings asks whether commercial attention followed the silver medalist more aggressively than the gold medalist.',
    'This illustrative demo shows how advertising disclosures, broadcast monitoring logs, and public reward circulars could be compared during a review.',
    'No specific primary records are linked in this demo, so the sponsorship counts, airtime comparison, and reward claim remain unverified.',
  ],
  sourceName: 'CivicLens Sports Desk',
  author: 'National Sports Bureau Desk',
  publishedAt: '2026-09-25T10:30:00Z',
  category: 'Business',
  location: {
    area: 'National Sports Bureau',
    district: 'National Sports Division',
    state: 'India',
    country: 'India',
  },
  imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=1200&auto=format&fit=crop',
  imageCaption: 'Athletes competing under stadium lights during a national sporting event.',
  claimsCount: 4,
  unresolvedQuestionsCount: 2,
  citizenReportsCount: 0,
  claims: [
    {
      id: 'claim-sports-001',
      claimText: 'The silver medalist secured 14 new commercial brand contracts within 30 days of the finals, while the gold medalist signed 3.',
      speakerOrSource: 'ASCI corporate registry and agency press releases',
      status: 'Needs verification',
      statusExplanation: 'No specific corporate filing or agency announcement is linked, so the contract count cannot be verified.',
      evidence: [
        {
          id: 'ev-sports-001',
          isDemo: true,
          type: 'Official document',
          title: 'ASCI corporate disclosure index',
          description: 'Illustrative placeholder for sponsorship disclosures and agency releases.',
          date: '2026-09-20',
          uploaderPseudonym: 'SportsDesk_Verified',
          provenanceNote: 'Demo record; direct filing and announcement links were not supplied.',
        },
      ],
      missingInformation: [],
      generatedQuestions: ['Were all 17 agreements active contracts or did some represent campaign renewals?'],
    },
    {
      id: 'claim-sports-002',
      claimText: 'The national broadcast network allocated 78% more prime-time coverage to the silver medalist’s homecoming.',
      speakerOrSource: 'Independent broadcast media monitoring agency',
      status: 'Needs verification',
      statusExplanation: 'No specific broadcast monitoring log is linked, so the airtime comparison cannot be verified.',
      evidence: [
        {
          id: 'ev-sports-002',
          isDemo: true,
          type: 'Dataset',
          title: 'Prime-time homecoming monitoring log',
          description: 'Illustrative placeholder for time-coded broadcast minutes.',
          date: '2026-09-19',
          uploaderPseudonym: 'MediaWatch_India',
          provenanceNote: 'Demo record; no public monitoring log was supplied.',
        },
      ],
      missingInformation: ['Comparable regional-language network minutes.', 'Full methodology for classifying repeat segments.'],
      generatedQuestions: ['Does the difference persist after including regional and digital broadcasts?'],
    },
    {
      id: 'claim-sports-003',
      claimText: 'The government sports development scheme withheld state prize allocation from the gold medalist.',
      speakerOrSource: 'Viral social media post',
      status: 'Needs verification',
      statusExplanation: 'No specific ministry circular or payment record is linked, so the reward claim cannot be verified.',
      evidence: [
        {
          id: 'ev-sports-003',
          isDemo: true,
          type: 'Official document',
          title: 'Ministry sports reward circular',
          description: 'Illustrative placeholder for an official reward circular or payment record.',
          date: '2026-09-18',
          uploaderPseudonym: 'CivicAuditor',
          provenanceNote: 'Demo record; no specific public circular or payment record was supplied.',
        },
      ],
      missingInformation: [],
      generatedQuestions: ['Was any separate state-level honorarium delayed despite the national grant?'],
    },
    {
      id: 'claim-sports-004',
      claimText: 'The silver medalist’s follower growth exceeded the gold medalist by 500% in 48 hours.',
      speakerOrSource: 'Unaudited social API scraping snapshots',
      status: 'Needs verification',
      statusExplanation: 'The screenshots show a sharp difference, but they do not provide an auditable API methodology, baseline timestamps, or bot-adjusted counts.',
      evidence: [
        {
          id: 'ev-sports-004',
          isDemo: true,
          type: 'External source',
          title: 'Social growth comparison snapshots',
          description: 'Unaudited screenshots claiming a 48-hour follower-growth comparison.',
          date: '2026-09-21',
          uploaderPseudonym: 'OpenDataObserver',
          provenanceNote: 'Community-submitted snapshots; platform export and collection method not supplied.',
        },
      ],
      missingInformation: ['Platform export with timestamps.', 'Bot and duplicate-account adjustment methodology.'],
      generatedQuestions: ['What were the verified baseline counts immediately before the finals?'],
    },
  ],
};
